### PR TITLE
Update to ModularUI 3.0.6, fix creative inventory desync

### LINKED ISSUE #36: Incompatible with Modular UI 2.5.0-rc5
[18:38:48] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method com/cleanroommc/retrosophisticatedbackpacks/tileentity/BackpackTileEntity.buildUI(Lcom/cleanroommc/modularui/factory/GuiData;Lcom/cleanroommc/modularui/value/sync/PanelSyncManager;Lcom/cleanroommc/modularui/screen/UISettings;)Lcom/cleanroommc/modularui/screen/ModularPanel; is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_452]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_452]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_452]
Caused by: java.lang.AbstractMethodError: Method com/cleanroommc/retrosophisticatedbackpacks/tileentity/BackpackTileEntity.buildUI(Lcom/cleanroommc/modularui/factory/GuiData;Lcom/cleanroommc/modularui/value/sync/PanelSyncManager;Lcom/cleanroommc/modularui/screen/UISettings;)Lcom/cleanroommc/modularui/screen/ModularPanel; is abstract
	at com.cleanroommc.retrosophisticatedbackpacks.tileentity.BackpackTileEntity.buildUI(BackpackTileEntity.kt) ~[BackpackTileEntity.class:?]
	at com.cleanroommc.modularui.factory.AbstractUIFactory.createPanel(AbstractUIFactory.java:34) ~[AbstractUIFactory.class:?]
	at com.cleanroommc.modularui.factory.GuiManager.open(GuiManager.java:74) ~[GuiManager.class:?]
	at com.cleanroommc.modularui.factory.TileEntityGuiFactory.open(TileEntityGuiFactory.java:41) ~[TileEntityGuiFactory.class:?]
	at com.cleanroommc.retrosophisticatedbackpacks.tileentity.BackpackTileEntity.openGui(BackpackTileEntity.kt:38) ~[BackpackTileEntity.class:?]
	at com.cleanroommc.retrosophisticatedbackpacks.block.BackpackBlock.func_180639_a(BackpackBlock.kt:205) ~[BackpackBlock.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_452]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_452]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

### PR DESCRIPTION
**Pull request by Axis-Denied**
I want to preface this by saying that these changes aren't quite fully finished yet, but barring the fourth entry in the following list, it should at the very least be stable. I was hoping to get some review from contributors since they'd know far more about the mod's inner workings than I would.
Naturally, I understand if this PR ends up closed for further improvements.

This PR intends to fix #36, and take a crack at #22 and #33.

1. In order to avoid a slot count check in ModularSlot which causes a crash, I added a bypass boolean field (and count field) to DelegatedItemHandler.  The code to recover the old 0 slot functionality is commented out in UpgradeSlotUpdateGroup. I didn't encounter any serious issues regarding this for now, so I left it be.
2. I changed how the share tag is implemented for the BackpackItem, which appeared to fix the issue with the creative inventory in multiplayer (and possibly other desyncs). Upgrading the backpack also started to preserve data as well.
3. ~~Sometimes, whenever an item is placed into one of the Filter upgrades' phantom slots, the item is dropped
 on the ground. I have yet to find a fix for this, mostly because it doesn't occur very often.~~ Has been fixed.
4. ~~**Arguably the most egregious issue, in some cases whenever buttons that change the layout are pressed (upgrade configuration, for instance), disabled widgets will render briefly before disappearing. This started occuring after the jump to 2.5.0 if I recall correctly. I have yet to find a fix for this as well.**~~ Has been fixed.
5. Almost forgot to mention, I added NEA to the build.gradle.

### CODE REVIEW

**Comment by Axis-Denied** [comment]
Currently, the Settings panel also crashes whenever NEA is not present. This appears to be due to ModularPanel referencing NEAConfig, despite it not being there. Mirroring that class and its dependencies on our end fixes this, but I don't know what your policy on including some of NEA's code is (even if it's skeletal).

**Comment by ChAoSUnItY** [comment]
Thanks for the contribution for the update of MUI and patches for desync issues!

For the NEA, it is required as MUI's author stated, so as long as the build does not require NEA to be able to launch, I'm pretty fine with the deal.

As for other buggy GUI and desync issue fixes, I will later launch and see if there is any other potential ways to fix.

**Comment by brachy84** [comment]
Whats the nea crash? ModularPanel only references NEAConfig if nea is loaded.

**Comment by ChAoSUnItY** [comment]
My assumption on the tab widget being temporarily rendered upon other being clicked is that current logic requires 2 steps (or cycle) to fully reset the state, ideally this should be done in 1 step.

**Comment by Axis-Denied** [comment]
Also, that issue with the NEAConfig started to happen again, this time regardless of the dev environment. Is that mod actually required? I noticed some code that checks if its loaded before using config values. I don't think the check is going to stop the classloader since its imported, provided the mod isn't required. I wonder if there's Java-related trickery going on here.

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/cleanroommc/neverenoughanimations/NEAConfig
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:47)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1078)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:399)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:125)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:42)
	at com.cleanroommc.relauncher.wrapper.RelaunchMainWrapper.main(RelaunchMainWrapper.java:20)
Caused by: java.lang.NoClassDefFoundError: com/cleanroommc/neverenoughanimations/NEAConfig
	at com.cleanroommc.modularui.screen.ModularPanel.getAnimator(ModularPanel.java:759)
	at com.cleanroommc.modularui.screen.ModularPanel.onOpen(ModularPanel.java:240)
	at com.cleanroommc.retrosophisticatedbackpacks.client.gui.BackpackSettingPanel.onOpen(BackpackSettingPanel.kt:92)

**Comment by Axis-Denied** [comment]
Okay, so I evidently didn't go back and check the shouldAnimate() calls in this mod's panel classes when 2.5.0 support was added. That method has the loaded check, it seems, but it gets overridden without calling super. Adding a super call fixed it, it seems.
I don't know if voiding super behavior was intended, though. If it was, I can add the mod loaded check in directly instead.

**Comment by Axis-Denied** [comment]
As far as I know, the only issue remaining is the item dropping. That, and the upgrade slots go dark if you open the settings tab.
I wonder if one of the widgets is erroneously sending the received click back to vanilla behavior. I did some stack trace printing and found some client-side calls of the GuiContainer methods that didn't originate from ModularUI's handler. These only seem to occur if the phantom slots are hovered (and inconsistently at that), items aren't dropped if you are on the other parts of the expanded filter tab.

**Comment by Axis-Denied** [comment]
After some analysis, I have a theory:
Two mouse inputs occur, the click and then the release. The click performs as expected, normal phantom slot interactions occur. It's the release where the problem starts. Since the upgrade items just got modified, the tab widgets need to be reconstructed since the UpgradeWrapper changed. The release sometimes occurs right after this happens, but before the newly created widgets have finished resizing, causing them to have 0'd out areas and thus be unhoverable. This makes them unclickable, causing it to divert to vanilla's gui release code, which looks for a slot at that point that doesn't exist there. No slot means the item is dropped.
(At least, that's what I think happens. I don't have a full grasp on how resizing is done, but outright preventing expanded tab widget reconstruction seemed to fix the bug, so that's my target for now)
I'll see if I can add in a way to just swap out the wrapper instead of reconstructing the widgets each time.

**Comment by Axis-Denied** [comment]
That marks the end of the glaring issues I found with the PR, it should be ready for further review now.

File: src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/item/BackpackItem.kt [hunk 1]
```diff
@@ -229,10 +239,14 @@ class BackpackItem(
         }
     }
 
-    override fun buildUI(data: PlayerInventoryGuiData, syncManager: PanelSyncManager): ModularPanel {
+    override fun buildUI(data: PlayerInventoryGuiData, syncManager: PanelSyncManager, uiSettings: UISettings): ModularPanel {
         val stack = data.usedItemStack
         val wrapper = stack.getCapability(Capabilities.BACKPACK_CAPABILITY, null)!!
-        return BackpackGuiHolder.ItemStackGuiHolder(wrapper).buildUI(data, syncManager)
+        val slotIndex = if (data.inventoryType == InventoryType.PLAYER_INVENTORY) data.slotIndex else null
+        val containerSupplier: Supplier<ModularContainer> = Supplier {BackpackContainer(wrapper,slotIndex)}
```
Comment (ChAoSUnItY) [inline src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/item/BackpackItem.kt]: Rewrite as follow:

```kt
val containerSupplier = () -> BackpackContainer(wrapper, slotIndex)
```

File: src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/widgets/slot/BackpackSlot.kt [hunk 2]
```diff
@@ -137,203 +147,111 @@ class BackpackSlot(private val panel: BackpackPanel, private val wrapper: Backpa
...
+                val memoryStack = slot.getMemoryStack()
 
-        if (isInSettingMode) drawSettingStack(context, widgetTheme)
-        else drawNormalStack(context, widgetTheme)
+                super.draw(context, widgetThemeEntry)
+
+                if (slot.stack.isEmpty && !memoryStack.isEmpty)
+                    drawMemoryStack(memoryStack, context, widgetTheme)
+
+            }//drawNormalStack(context, widgetTheme)
```
Comment (ChAoSUnItY) [inline src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/widgets/slot/BackpackSlot.kt]: Remove unused code.

**Review by ChAoSUnItY — CHANGES_REQUESTED** [review]
Additional suggestion on widget theme fetching, there's a lot of places using the same logic:

```kt
widgetTheme?.theme ?: WidgetTheme.getDefault().theme
```

Rewrite this into an extension function would be helpful as later we can just call the function instead of rewriting similar logic again:

```kt
fun WidgetThemeEntry<out WidgetTheme>?.getThemeOrDefault(): WidgetTheme =
        this?.theme ?: WidgetTheme.getDefault().theme
```

File: src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/widgets/slot/BackpackSlot.kt [hunk 3]
```diff
@@ -55,13 +63,15 @@ class BackpackSlot(private val panel: BackpackPanel, private val wrapper: Backpa
 
         if (!stack.isEmpty) {
             super.buildTooltip(stack, tooltip)
-            formattedCount = NumberFormat.formatWithMaxDecimals(stack.count.toDouble(), 2)
-            formattedStackLimit = NumberFormat.formatWithMaxDecimals(slot.getItemStackLimit(stack).toDouble(), 2)
+
+            //NumberFormat.format(amount, NumberFormat.AMOUNT_TEXT);
```
[the remark this answers is not in the document]
Comment (Axis-Denied) [reply src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/widgets/slot/BackpackSlot.kt]: Should be in my next commit.

**Comment by Axis-Denied** [comment]
Anyways, I'm modifying TabWidget to use a DoubleSupplier for its shift tied to a separate field. Then I can add the following to updateUpgradeSlots:
```kotlin
        // Shifted forward to account for settings tab.
        var tabDisplayIndex = 1

        // Sync all tabs to their corresponding upgrade
        for (slotIndex in 0 until backpackWrapper.upgradeSlotsSize()) {
            val slot = upgradeSlotWidgets[slotIndex]
            val stack: ItemStack = slot.slot.stack
            val item = stack.item

            val tabWidget = tabWidgets[tabIndex]

            if (!(item is UpgradeItem && item.hasTab)){
                tabWidget.isEnabled = false
                tabWidget.expandedWidget = null
                tabIndex++
                continue
            }

            val upgradeSlotGroup = upgradeSlotGroups[slotIndex]
            val wrapper: UpgradeWrapper<*> = stack.getCapability(Capabilities.UPGRADE_CAPABILITY, null) ?: continue
            tabWidget.showExpanded = wrapper.isTabOpened
            tabWidget.isEnabled = true
            // Ensure correct tab position
            tabWidget.tabOrder = tabDisplayIndex
            tabWidget.tabIcon = ItemDrawable(slot.slot.stack)

            /* code to add the widgets, omitted for brevity */

            context.recipeViewerSettings.addExclusionArea(tabWidget.expandedWidget)
            tabIndex++
            tabDisplayIndex++
        }
```
This should ensure the tab isn't shifted like in the earlier example with the stack upgrade. Since TabWidget is using a supplier, it should update as this variable is changed.

In TabWidget:
```kotlin
        size(TAB_TEXTURE.width, TAB_TEXTURE.height).top({tabOrder * 30.0}, Unit.Measure.PIXEL)
```
The measures are listed as internal so this could be seen as a bit of a hack.

**Comment by Axis-Denied** [comment]
The changes make it look like this. Let me know which you prefer:
image

**Comment by ChAoSUnItY** [comment]
Feel free to re-request review from me when you're done to the patches.

File: src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/UpgradeSlotUpdateGroup.kt [hunk 4]
```diff
@@ -48,6 +48,7 @@ class UpgradeSlotUpdateGroup(
 
         syncManager.syncValue("adv_common_filter_delegation_$slotIndex", advancedCommonFilterStackHandler)
 
+        advancedCommonFilterStackHandler.delegatedStackHandler.bypassSizeCheck = true
```
Comment (ChAoSUnItY) [inline src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/UpgradeSlotUpdateGroup.kt]: Ditto.

File: src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/UpgradeSlotUpdateGroup.kt [hunk 5]
```diff
@@ -91,6 +92,8 @@ class UpgradeSlotUpdateGroup(
 
             slot
         }
+        commonFilterStackHandler.delegatedStackHandler.bypassSizeCheck = false
+        advancedCommonFilterStackHandler.delegatedStackHandler.bypassSizeCheck = false
```
Comment (ChAoSUnItY) [inline src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/UpgradeSlotUpdateGroup.kt]: Ditto.

**Review by ChAoSUnItY — CHANGES_REQUESTED** [review]

File: src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/inventory/DelegatedItemHandler.kt [hunk 6]
```diff
@@ -4,9 +4,25 @@ import net.minecraft.item.ItemStack
...
+    var bypassSizeCheck = false
+
+
+    override fun getSlots(): Int{
+        val current = delegated().slots
+        if (current == 0 && bypassSizeCheck) {
+            return wrappedSlotAmount
+        }
+        return current;
+    }
```
[the remark this answers is not in the document]
Comment (Axis-Denied) [reply src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/inventory/DelegatedItemHandler.kt]: Got it.

File: src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/widgets/TabWidget.kt [hunk 7]
```diff
@@ -19,13 +21,21 @@ class TabWidget(
...
     var expandedWidget: ExpandedTabWidget? = null
         set(value) {
             if (value != null) {
                 if (expandDirection == ExpandDirection.LEFT)
                     value.right(0)
 
-                child(value.setEnabledIf { showExpanded })
+                child(value.setEnabledIfAndEnabled { showExpanded })
+            }else{
+                child(null)
```
[the remark this answers is not in the document]
Comment (Axis-Denied) [reply src/main/kotlin/com/cleanroommc/retrosophisticatedbackpacks/client/gui/widgets/TabWidget.kt]: Forgot to mention I fixed this

**Review by ChAoSUnItY — APPROVED** [review]
